name: Java Release

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'The run ID of the build pipeline to download the artifact from'
        required: true
        type: string
      environment:
        type: choice
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        options:
          - 'staging'
          - 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: java-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.build_run_id }}
          path: ./downloaded-artifact

      - name: Verify artifact
        run: ls -lh ./downloaded-artifact

      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          echo "Deploying artifact from build run ${{ github.event.inputs.build_run_id }} to ${{ github.event.inputs.environment }} environment..."
          # Your deployment script here, using the downloaded artifact and the input values
          # Example: java -jar ./downloaded-artifact/your-app.jar --env=${{ github.event.inputs.environment }}
